INSERT OR IGNORE INTO movies(slug,title,original_title,type,description,release_year,duration_minutes,status,quality,age_rating,country,poster_url,backdrop_url,video_key,video_url,featured) VALUES('hanh-trinh-sao-bang','Hành Trình Sao Băng','Meteor Journey','movie','Một phi hành đoàn trẻ vượt qua vùng không gian bị lãng quên để tìm tín hiệu cuối cùng từ Trái Đất.',2026,104,'published','HD','T13','Việt Nam','/assets/posters/hanh-trinh-sao-bang.svg','/assets/backdrops/hanh-trinh-sao-bang.svg',NULL,'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',1);
INSERT OR IGNORE INTO genres(name,slug) VALUES('Khoa học viễn tưởng','khoa-hoc-vien-tuong');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='hanh-trinh-sao-bang' AND g.name='Khoa học viễn tưởng';
INSERT OR IGNORE INTO genres(name,slug) VALUES('Phiêu lưu','phieu-luu');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='hanh-trinh-sao-bang' AND g.name='Phiêu lưu';
INSERT OR IGNORE INTO movies(slug,title,original_title,type,description,release_year,duration_minutes,status,quality,age_rating,country,poster_url,backdrop_url,video_key,video_url,featured) VALUES('thanh-pho-sau-mua','Thành Phố Sau Mưa','City After Rain','series','Hai người xa lạ lần theo một cuốn nhật ký cũ và khám phá những bí mật bị chôn vùi dưới thành phố.',2025,48,'published','Full HD','T16','Hàn Quốc','/assets/posters/thanh-pho-sau-mua.svg','/assets/backdrops/thanh-pho-sau-mua.svg',NULL,'',0);
INSERT OR IGNORE INTO genres(name,slug) VALUES('Tâm lý','tam-ly');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='thanh-pho-sau-mua' AND g.name='Tâm lý';
INSERT OR IGNORE INTO genres(name,slug) VALUES('Bí ẩn','bi-an');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='thanh-pho-sau-mua' AND g.name='Bí ẩn';
INSERT OR IGNORE INTO movies(slug,title,original_title,type,description,release_year,duration_minutes,status,quality,age_rating,country,poster_url,backdrop_url,video_key,video_url,featured) VALUES('tan-so-cuoi-cung','Tần Số Cuối Cùng','The Last Frequency','movie','Một kỹ sư vô tuyến nhận được tín hiệu báo trước các sự kiện chưa xảy ra.',2026,97,'published','HD','T16','Nhật Bản','/assets/posters/tan-so-cuoi-cung.svg','/assets/backdrops/tan-so-cuoi-cung.svg',NULL,'',0);
INSERT OR IGNORE INTO genres(name,slug) VALUES('Khoa học viễn tưởng','khoa-hoc-vien-tuong');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='tan-so-cuoi-cung' AND g.name='Khoa học viễn tưởng';
INSERT OR IGNORE INTO genres(name,slug) VALUES('Giật gân','giat-gan');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='tan-so-cuoi-cung' AND g.name='Giật gân';
INSERT OR IGNORE INTO movies(slug,title,original_title,type,description,release_year,duration_minutes,status,quality,age_rating,country,poster_url,backdrop_url,video_key,video_url,featured) VALUES('mua-he-khong-ten','Mùa Hè Không Tên','Nameless Summer','movie','Nhóm bạn cũ trở về thị trấn biển và hoàn thành lời hứa còn dang dở từ thời niên thiếu.',2024,111,'published','HD','P','Việt Nam','/assets/posters/mua-he-khong-ten.svg','/assets/backdrops/mua-he-khong-ten.svg',NULL,'',0);
INSERT OR IGNORE INTO genres(name,slug) VALUES('Tình cảm','tinh-cam');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='mua-he-khong-ten' AND g.name='Tình cảm';
INSERT OR IGNORE INTO genres(name,slug) VALUES('Thanh xuân','thanh-xuan');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='mua-he-khong-ten' AND g.name='Thanh xuân';
INSERT OR IGNORE INTO movies(slug,title,original_title,type,description,release_year,duration_minutes,status,quality,age_rating,country,poster_url,backdrop_url,video_key,video_url,featured) VALUES('ho-so-bong-dem','Hồ Sơ Bóng Đêm','Night Files','series','Một đội điều tra độc lập xử lý những vụ án mà hồ sơ chính thức đã khép lại quá sớm.',2026,52,'published','Full HD','T18','Thái Lan','/assets/posters/ho-so-bong-dem.svg','/assets/backdrops/ho-so-bong-dem.svg',NULL,'',0);
INSERT OR IGNORE INTO genres(name,slug) VALUES('Hình sự','hinh-su');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='ho-so-bong-dem' AND g.name='Hình sự';
INSERT OR IGNORE INTO genres(name,slug) VALUES('Bí ẩn','bi-an');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='ho-so-bong-dem' AND g.name='Bí ẩn';
INSERT OR IGNORE INTO movies(slug,title,original_title,type,description,release_year,duration_minutes,status,quality,age_rating,country,poster_url,backdrop_url,video_key,video_url,featured) VALUES('nguoi-giu-khu-rung','Người Giữ Khu Rừng','Forest Keeper','movie','Một kiểm lâm trẻ đối đầu với âm mưu khai thác trái phép trong khu bảo tồn cuối cùng của vùng.',2025,102,'published','HD','T13','Việt Nam','/assets/posters/nguoi-giu-khu-rung.svg','/assets/backdrops/nguoi-giu-khu-rung.svg',NULL,'',0);
INSERT OR IGNORE INTO genres(name,slug) VALUES('Hành động','hanh-dong');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='nguoi-giu-khu-rung' AND g.name='Hành động';
INSERT OR IGNORE INTO genres(name,slug) VALUES('Phiêu lưu','phieu-luu');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='nguoi-giu-khu-rung' AND g.name='Phiêu lưu';

INSERT OR IGNORE INTO movies(slug,title,original_title,type,description,release_year,duration_minutes,status,quality,age_rating,country,tags,poster_url,backdrop_url,video_key,video_url,featured) VALUES('yosuga-no-sora','Yosuga no Sora','Yosuga no Sora: In Solitude When We Are Least Alone (ヨスガノソラ)','series','Sau khi cha mẹ qua đời trong một vụ tai nạn, Haruka Kasugano và cô em gái sinh đôi Sora mất đi chỗ dựa duy nhất. Hai anh em quyết định rời thành phố và chuyển đến một thị trấn vùng quê, nơi họ từng trải qua những mùa hè bên người ông quá cố. Ban đầu, mọi thứ nơi đây vẫn quen thuộc và yên bình. Tuy nhiên, Haruka dần nhớ lại những ký ức từ thời thơ ấu. Những ký ức tưởng như đã bị lãng quên ấy bắt đầu làm thay đổi cuộc sống của hai anh em.',2010,25,'published','HD','T18','Nhật Bản','Loạn luân||Vũ trụ thay thế||Sinh đôi||Dàn nhân vật||Harem','/assets/posters/yosuga-no-sora.svg','/assets/backdrops/yosuga-no-sora.svg',NULL,'',0);
INSERT OR IGNORE INTO genres(name,slug) VALUES('Drama','drama');
INSERT OR IGNORE INTO genres(name,slug) VALUES('Ecchi','ecchi');
INSERT OR IGNORE INTO genres(name,slug) VALUES('Lãng mạn','lang-man');
INSERT OR IGNORE INTO genres(name,slug) VALUES('Harem','harem');
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='yosuga-no-sora' AND g.name='Drama';
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='yosuga-no-sora' AND g.name='Ecchi';
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='yosuga-no-sora' AND g.name='Lãng mạn';
INSERT OR IGNORE INTO movie_genres(movie_id,genre_id) SELECT m.id,g.id FROM movies m,genres g WHERE m.slug='yosuga-no-sora' AND g.name='Harem';
WITH RECURSIVE episode_numbers(number) AS (SELECT 1 UNION ALL SELECT number + 1 FROM episode_numbers WHERE number < 12)
INSERT OR IGNORE INTO episodes(movie_id,season_number,episode_number,title,duration_minutes,status,video_key,video_url)
SELECT m.id,1,episode_numbers.number,printf('Tập %02d',episode_numbers.number),25,'published',NULL,'' FROM movies m CROSS JOIN episode_numbers WHERE m.slug='yosuga-no-sora';
UPDATE movies SET featured=0 WHERE slug='hanh-trinh-sao-bang';
UPDATE movies SET backdrop_url='/assets/banners/yosuga-no-sora.jpg',featured=1 WHERE slug='yosuga-no-sora';
